### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by snwflake** [snwflake/tanku-bot#1]
### `/booster`-command:
- [ ] validate input against enums
- [ ] enhance feedback in error cases
- [ ] check for already active boosters in `$slot` 
- [ ] allow for second booster to be enabled with first already being active
